name: Build and Environment Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Firebase environment variables
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      - name: Verify environment variables (safely)
        run: |
          echo "Checking if Firebase environment variables are set (without exposing values):"
          echo "API_KEY set: $([[ -n "$NEXT_PUBLIC_FIREBASE_API_KEY" ]] && echo 'yes' || echo 'no')"
          echo "AUTH_DOMAIN set: $([[ -n "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" ]] && echo 'yes' || echo 'no')"
          echo "PROJECT_ID set: $([[ -n "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]] && echo 'yes' || echo 'no')"
          echo "STORAGE_BUCKET set: $([[ -n "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" ]] && echo 'yes' || echo 'no')"
          echo "MESSAGING_SENDER_ID set: $([[ -n "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" ]] && echo 'yes' || echo 'no')"
          echo "APP_ID set: $([[ -n "$NEXT_PUBLIC_FIREBASE_APP_ID" ]] && echo 'yes' || echo 'no')"
          echo "API_KEY starts with 'AIza': $([[ "$NEXT_PUBLIC_FIREBASE_API_KEY" == AIza* ]] && echo 'yes' || echo 'no')"

      - name: Build application
        run: npm run build 